import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
//@ts-ignore
import "./globals.css";

export const metadata: Metadata = {
  title: "Government",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <Navbar/>
          <main className="flex-grow">
            {children}
          </main> 
          <Footer/>
        </div>
      </body>
    </html>
  );
}




